### ISSUE TITLE
Door activated on boot. 

### ISSUE THREAD

**Issue by oriolism** [ElectronHacks/MQTT_ESP8266_Garage_Door#1]
Im having an issue with the ESP8266 E12. It appears that on boot the ESP activate the pins and for this reason the relay is activated. I already tried changing the output to the other pins but without luck. Any Ideas of how can i fix this?

**Comment by jhottell** [comment]
That's odd, on mine it doesn't do this, I am using an esp-07 on a breakout board. What ESP board are you using? The problem probably lies with the ESP8266 behavior. If the module looses its load or goes into program mode it sends all the pins high which sucks. I think it does blink the pins high on reboot as well but it must be so fast that it doesn't trigger my relay.
 
On other projects I added a fail safe PNP transistor in line with the power of the NPN transistor that powers the relay. if all pins are high no signal can pass the PNP transistor, in the code add an enable output and pull the signal low to the PNP transistor to allow the other signal to pass through.

**Comment by oriolism** [comment]
This was fixed, it was the retain value on the mqtt server. 

Thanks!
